### ISSUE TITLE
Exercise 4: Backup and Restore

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/SQL-Track#4]
https://github.com/damilola-dealdey/SQL-Track/tree/master/Ex4

Take backup of the db you created for practice/exercise and send it to me. Now create a new database named "restored" and restore that backup into this DB.

**Comment by segunadeleye** [comment]
Will these commands work without specifying the `-u` and `-p` flags?

**Comment by damilola-dealdey** [comment]
No, they won't . I omitted the flags for brevity.

**Comment by segunadeleye** [comment]
Closing the issue but add them. You don't have to use real user or password.
